# Configure main menu and social menu
#[[main]]
#identifier = "portfolio"
#name = "Portfolio"
#url = "/portfolio"
#[main.params]
#icon = "home"
#newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/itsmeguto"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/itsmeguto17"

[social.params]
icon = "brand-twitter"
